package pt.ipca.escutas.resources

/**
 * Defines strings used in types that aren't related to the layout, such as controllers or services.
 */
object Strings {
    const val MSG_FIELD_BLANK = "O campo não pode estar vazio."
    const val MSG_DATE_INVALID = "A data de fim é menor que a data de início"
    const val MSG_INCORRECT_EMAIL = "O email está incorreto."
    const val MSG_INCORRECT_PASSWORDS = "As palavras-chave são diferentes."
    const val MSG_SMALL_PASSWORD = "A palavra-chave tem que ter pelo menos 6 caracteres."
    const val MSG_NO_USER_AVAILABLE = "Não existe nenhum utilizador disponível."
    const val MSG_USER_CREATED = "O utilizador foi criado com sucesso."
    const val MSG_FAILED_USER_CREATE = "Não foi possível criar o utilizador."
    const val MSG_USER_DELETED = "Utilizador removido com sucesso."
    const val MSG_FAILED_USER_DELETE = "Não foi possível remover o utilizador."
    const val MSG_USER_EMAIL_UPDATE = "O email do utilizador foi atualizado com sucesso."
    const val MSG_FAILED_USER_EMAIL_UPDATE = "Não foi possível atualizar o email do utilizador."
    const val MSG_USER_PASSWORD_UPDATE = "A palavra-chave do utilizador foi atualizada com sucesso."
    const val MSG_FAILED_USER_PASSWORD_UPDATE = "Não foi possível atualizar a palavra-chave do utilizador."
    const val MSG_EMAIL_SENT = "O email foi enviado."
    const val MSG_FAIL_EMAIL = "O email não foi enviado."
    const val MSG_USER_LOGIN = "O utilizador entrou."
    const val MSG_FAIL_USER_LOGIN = "O utilizador não conseguiu entrar."
    const val MSG_FAIL_STORAGE_CREATE = "A operação de criação de um ficheiro remoto falhou."
    const val MSG_FAIL_STORAGE_READ = "A operação de leitura de um ficheiro remoto falhou."
    const val MSG_FAIL_STORAGE_UPDATE = "A operação de atualização de um ficheiro remoto falhou."
    const val MSG_FAIL_STORAGE_DELETE = "A operação de eliminação de um ficheiro remoto falhou."
    const val MSG_FAIL_DATABASE_GET = "Erro ao obter resultados."
    const val MSG_FAIL_DATABASE_ADD = "Erro ao adicionar registo."
    const val MSG_FAIL_DATABASE_REMOVE = "Erro ao remover registo."
    const val MSG_FAIL_DATABASE_UPDATE = "Erro ao actualizar registo."
    const val MSG_STORAGE_USER_LOCATION = "users"
    const val MSG_STORAGE_GROUP_LOCATION = "groups"
    const val MSG_ABOUT_ACT_TITLE = "Sobre"
    const val MSG_PASSWORD_REC_ACT_TITLE = "Recuperar Palavra-Chave"
    const val MSG_PERSONAL_AREA_ACT_TITLE = "Área Pessoal"
    const val MSG_REGISTRATION_AREA_ACT_TITLE = "Registo"
    const val MSG_STORAGE_EVENT_LOCATION = "events"
    const val MSG_STORAGE_NEWS_LOCATION = "news"
}
